# Generated by Django 3.1.7 on 2021-05-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('billing_method', models.BooleanField(default=0)),
                ('network_demand_guest', models.BooleanField(default=0)),
                ('network_demand_management', models.BooleanField(default=0)),
                ('network_demand_test', models.BooleanField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('last_state', models.IntegerField(default=0)),
                ('reason', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('upload_speed', models.IntegerField(default=0)),
                ('download_speed', models.IntegerField(default=0)),
                ('flow', models.BigIntegerField(default=0)),
                ('flow_threshold', models.BigIntegerField()),
                ('online_user_cnt', models.IntegerField(default=0)),
                ('max_user_number_cnt', models.IntegerField(default=0)),
                ('flow_limit_exceeded', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enable', models.BooleanField(default=True)),
                ('connection_mode', models.CharField(default='nat', max_length=10)),
                ('hid_enable', models.BooleanField(default=False)),
                ('relative_radios', models.IntegerField(default=3)),
                ('max_user_number', models.IntegerField(default=10)),
                ('user_separation', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('privilege', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSIDAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='ppsk', max_length=10)),
                ('psk_encrypt_type', models.CharField(default='wpa2', max_length=20)),
                ('security_key', models.CharField(max_length=63)),
                ('security_key_type', models.CharField(default='AES', max_length=10)),
                ('dot1x_encrypt_type', models.CharField(max_length=20)),
                ('mac_auto_binding', models.BooleanField()),
                ('ssid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='api.ssid')),
            ],
        ),
        migrations.CreateModel(
            name='SiteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_user_cnt', models.IntegerField(default=0)),
                ('upload_speed', models.IntegerField(default=0)),
                ('download_speed', models.IntegerField(default=0)),
                ('flow', models.BigIntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esn', models.CharField(max_length=50)),
                ('uuid', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=20)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.network')),
            ],
        ),
    ]
